function allowable_labels = get_allowable_elecs(name)

if contains(name,'MP') % MUSC patient

    %
    allow_nums = num2cell(repmat((1:12)',6,1));
    allow_lr = [repmat({'L'},12*3,1);...
        repmat({'R'},12*3,1)];
    allow_letters = [repmat({'A'},12,1);...
        repmat({'AH'},12,1);...
        repmat({'PH'},12,1);...
        repmat({'A'},12,1);...
        repmat({'AH'},12,1);...
        repmat({'PH'},12,1)];
    allowable_labels = cellfun(@(x,y,z) ...
        sprintf('%s%s%d',x,y,z),allow_lr,allow_letters,...
        allow_nums,'Uniformoutput',false);
    %}
    %{
    allow_nums = num2cell(repmat((1:10)',6,1));
    allow_lr = [repmat({'L'},10*3,1);...
        repmat({'R'},10*3,1)];
    allow_letters = [repmat({'A'},10,1);...
        repmat({'AH'},10,1);...
        repmat({'PH'},10,1);...
        repmat({'A'},10,1);...
        repmat({'AH'},10,1);...
        repmat({'PH'},10,1)];
    allowable_labels = cellfun(@(x,y,z) ...
        sprintf('%s%s%d',x,y,z),allow_lr,allow_letters,...
        allow_nums,'Uniformoutput',false);
    %}

else % HUP patient

    %

    allow_nums = num2cell(repmat((1:12)',6,1));
    allow_lr = [repmat({'L'},12*3,1);...
        repmat({'R'},12*3,1)];
    allow_letters = [repmat({'A'},12,1);...
        repmat({'B'},12,1);...
        repmat({'C'},12,1);...
        repmat({'A'},12,1);...
        repmat({'B'},12,1);...
        repmat({'C'},12,1)];
    allowable_labels = cellfun(@(x,y,z) ...
        sprintf('%s%s%d',x,y,z),allow_lr,allow_letters,...
        allow_nums,'Uniformoutput',false);
    %}

    %{
    allow_nums = num2cell(repmat((1:10)',6,1));
    allow_lr = [repmat({'L'},10*3,1);...
        repmat({'R'},10*3,1)];
    allow_letters = [repmat({'A'},10,1);...
        repmat({'B'},10,1);...
        repmat({'C'},10,1);...
        repmat({'A'},10,1);...
        repmat({'B'},10,1);...
        repmat({'C'},10,1)];
    allowable_labels = cellfun(@(x,y,z) ...
        sprintf('%s%s%d',x,y,z),allow_lr,allow_letters,...
        allow_nums,'Uniformoutput',false);
    %}

end

end